version: '3.3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.2
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  kafka01:
    image: confluentinc/cp-kafka:5.5.2
    ports:
      - 9092:9092
    environment:
      KAFKA_HEAP_OPTS: -Xmx300M -Xms300M
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://kafka01:9090,OUTSIDE://kafka01:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka01:9090,OUTSIDE://kafka01:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
  kafka02:
    image: confluentinc/cp-kafka:5.5.2
    ports:
      - 9093:9093
    environment:
      KAFKA_HEAP_OPTS: -Xmx300M -Xms300M
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://kafka02:9090,OUTSIDE://kafka02:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka02:9090,OUTSIDE://kafka02:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
