version: '3.3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.2
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  kafka01:
    image: confluentinc/cp-kafka:5.5.2
    ports:
      - 9070:9070
    environment:
      KAFKA_HEAP_OPTS: -Xmx300M -Xms300M
      KAFKA_ZOOKEEPER_CONNECT: ${MY_HOST_IP}:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: OUTSIDE://kafka01:9070
      KAFKA_ADVERTISED_LISTENERS: OUTSIDE://${MY_HOST_IP}:9070
      KAFKA_INTER_BROKER_LISTENER_NAME: OUTSIDE
  kafka02:
    image: confluentinc/cp-kafka:5.5.2
    ports:
      - 9080:9080
    environment:
      KAFKA_HEAP_OPTS: -Xmx300M -Xms300M
      KAFKA_ZOOKEEPER_CONNECT: ${MY_HOST_IP}:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: OUTSIDE://kafka02:9080
      KAFKA_ADVERTISED_LISTENERS: OUTSIDE://${MY_HOST_IP}:9080
      KAFKA_INTER_BROKER_LISTENER_NAME: OUTSIDE
