version: '2.4'
networks:
  jenkins:
    driver: bridge
services:
  master:
    image: jenkins/jenkins:lts
    ports:
      - 8080:8080
      - 5005:5005
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,address=0.0.0.0:5005,server=y,suspend=n -Djava.util.logging.config.file=/logging.properties"
    volumes:
      - /var/tmp/jenkins_home:/var/jenkins_home
      - ./logging.properties:/logging.properties
    networks:
      - jenkins
  slave:
    image: jenkins/agent
    volumes:
      - /var/tmp/jenkins_slave_home:/workspace/remote
    command: "java -jar /usr/share/jenkins/slave.jar -jnlpUrl http://master:8080/computer/slave1/slave-agent.jnlp -secret 7208793d9fef46681eb51b5d3907d9046ed741c2b8cb9d19064b1373bed6b6ea"
    networks:
      - jenkins
