version: '3.3'
services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  prometheusproxy:
    image: "nginx:1.17.2"
    ports:
      - "8090:80"
    volumes:
      - ./myhttp.conf:/etc/nginx/conf.d/default.conf
      - ./user.wd:/etc/nginx/conf.d/user.wd
  actuator:
    image: huaminglin/spring-boot-actuator-demo:1.0-SNAPSHOT
    ports:
      - 8080:8080
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
  cadvisor:
    image: google/cadvisor:latest
    ports:
    - 8070:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
    - actuator
