version: '2.4'
services:
  server:
    image: tomcat:9.0.43
    ports:
      - 10080:8080
      - 10443:8443
      - 9999:9999
    environment:
      - "JAVA_OPTS=-Xms256M -Xmx256M -Dcom.sun.management.jmxremote.port=9999 -Dcom.sun.management.jmxremote.rmi.port=9999 -Djava.rmi.server.hostname=${DOCKER_HOST_IP} -Dcom.sun.management.jmxremote.authenticate=true -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.access.file=/tmp/non-existing-access -Dcom.sun.management.jmxremote.password.file=/tmp/non-existing-password"
