version: '3.3'
networks:
  jdk11:
    driver: bridge
services:
  server:
    image: openjdk:11.0.8-jdk
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
    networks:
      - jdk11
    privileged: true
  client:
    image: openjdk:11.0.8-jdk
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
    networks:
      - jdk11
