version: '3.3'
networks:
  frontend:
    ipam:
      config:
        - subnet: 172.120.0.0/24
services:
  prometheus:
    image: prom/prometheus
    networks:
      frontend:
        ipv4_address: 172.120.0.200
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    networks:
      frontend:
        ipv4_address: 172.120.0.203
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./dashboards:/etc/dashboards
  node-exporter:
    image: prom/node-exporter
    network_mode: "host"
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
