{
 "title": "JMX exporter prometheus",
 "description": "Complete dashboard using metrics from prometheus JMX exporter, with drill down per release > pod",
 "tags": [ "JVM" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "release", "label": "release", "query": "label_values(release)" },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(jvm_info{release=\"$release\"},kubernetes_pod_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Heap used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(jvm_memory_bytes_used{area=\"heap\",release=\"$release\"})*100) / sum(jvm_memory_bytes_max{area=\"heap\",release=\"$release\"})"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "dateTimeAsUS",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(process_start_time_seconds{release=\"$release\"})*1000"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds{release=\"$release\"})"
    }
   ]
  },
  {
   "title": "JVM Version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jvm_info{}" }
   ]
  },
  {
   "title": "Heap",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",release=\"$release\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Used {{kubernetes_pod_name}}"
    },
    {
     "expr": " jvm_memory_bytes_max{area=\"heap\",release=\"$release\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Max {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Non Heap",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"nonheap\",release=\"$release\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Used  {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "PS Eden Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{release=\"$release\", pool=\"PS Eden Space\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Max  {{kubernetes_pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{release=\"$release\", pool=\"PS Eden Space\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Used  {{kubernetes_pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{release=\"$release\", pool=\"PS Eden Space\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Committed  {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "PS Old Gen",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{release=\"$release\", pool=\"PS Old Gen\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Max  {{kubernetes_pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{release=\"$release\", pool=\"PS Old Gen\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Used  {{kubernetes_pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{release=\"$release\", pool=\"PS Old Gen\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Committed  {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "PS Survivor Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{release=\"$release\", pool=\"PS Survivor Space\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Max  {{kubernetes_pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{release=\"$release\", pool=\"PS Survivor Space\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Used  {{kubernetes_pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{release=\"$release\", pool=\"PS Survivor Space\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Committed  {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Metaspace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{release=\"$release\", pool=\"Metaspace\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Max {{kubernetes_pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{release=\"$release\", pool=\"Metaspace\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Used {{kubernetes_pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{release=\"$release\", pool=\"Metaspace\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Committed {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Compressed Class Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{release=\"$release\", pool=\"Compressed Class Space\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Max {{kubernetes_pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{release=\"$release\", pool=\"Compressed Class Space\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Used {{kubernetes_pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{release=\"$release\", pool=\"Compressed Class Space\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Committed {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Code Cache",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{release=\"$release\", pool=\"Code Cache\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Max {{kubernetes_pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{release=\"$release\", pool=\"Code Cache\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Used {{kubernetes_pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{release=\"$release\", pool=\"Code Cache\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Committed {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{release=~\"$release\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "JVM current threads  {{kubernetes_pod_name}}"
    },
    {
     "expr": "jvm_threads_daemon{release=~\"$release\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "JVM daemon threads {{kubernetes_pod_name}}"
    },
    {
     "expr": "jvm_threads_deadlocked{release=~\"$release\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "JVM deadlocked threads  {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{release=~\"$release\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{gc}}  {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "GC time / 1 min. rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{release=~\"$release\",kubernetes_pod_name=~\"$pod\"}[5m])",
     "legendFormat": "{{gc}} {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Class loading",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded{release=~\"$release\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "loaded  {{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}