version: '3.3'
services:
  master:
    image: redis:5.0
  slave:
    image: redis:5.0
    command: redis-server --slaveof redis-master 6379
    links:
      - master:redis-master
  client:
    image: redis:5.0
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
