version: '3.3'
networks:
  docker-demo:
    driver: bridge
services:
  client:
    image: postgres:12.1
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
    environment:
      - MY_ENV=abc
      - MY_ENV_02=${myenv2}
    networks:
      - docker-demo
