version: '3.3'
services:
  server:
    image: redis:5.0
    command: ["redis-server", "--appendonly", "yes", "--save", "10", "1"]
  client:
    image: redis:5.0
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
