version: '3.3'
networks:
  mongo:
    driver: bridge
services:
  repl01:
    image: mongo:4.2
    ports:
      - 27017:27017
    command: ["-replSet", "myrepl", "--port", "27017"]
    networks:
      - mongo
    restart: unless-stopped
  repl02:
    image: mongo:4.2
    ports:
      - 28017:27017
    command: ["-replSet", "myrepl", "--port", "27017"]
    networks:
      - mongo
    restart: unless-stopped
  repl03:
    image: mongo:4.2
    ports:
      - 29017:27017
    command: ["-replSet", "myrepl", "--port", "27017"]
    networks:
      - mongo
    restart: unless-stopped
  express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: repl01
      ME_CONFIG_OPTIONS_EDITORTHEME: 3024-night
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpress
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpress
      ME_CONFIG_MONGODB_ADMINUSERNAME: dbadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    networks:
      - mongo
    restart: unless-stopped
    depends_on: ["repl01"]
