version: '3'
networks:
  bridge:
    driver: bridge
services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.4.0"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
    networks:
      - bridge
  kibana:
    image: "docker.elastic.co/kibana/kibana:6.4.0"
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ES_HEAP_SIZE=1024m
    networks:
      - bridge
  logstash:
    image: "docker.elastic.co/logstash/logstash:6.4.0"
    ports:
      - "5044:5044"
      - "31311:31311"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    volumes:
      - $PWD/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    networks:
      - bridge
