version: '2.4'
services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./dashboards:/etc/dashboards
  micrometer:
    image: huaminglin/micrometer-demo:1.0-SNAPSHOT
    environment:
      - "_JAVA_OPTIONS=-Xms50m -Xmx100m"
    ports:
      - 8080:8080
    cpu_count: 2
    cpu_percent: 10
    cpus: 0.5
    cpuset: 0,1
    mem_limit: 512m
    memswap_limit: 512m
    mem_reservation: 512m
